In [1]:
%run ../__init__.py

In [2]:
targets

['Function',
 'Use',
 'Sharing',
 'Reporting',
 'Student_Type',
 'Position_Type',
 'Object_Type',
 'Pre_K',
 'Operating_Status']

In [3]:
budget_test = pd.read_csv('../data/budget_test.csv')

/opt/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (5,11) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [16]:
budget_test.head(20)

,Unnamed: 0,Object_Description,Program_Description,SubFund_Description,Job_Title_Description,Facility_or_Department,Sub_Object_Description,Location_Description,FTE,Function_Description,Position_Extra,Text_4,Total,Text_2,Text_3,Fund_Description,Text_1
0,180042,Student Meals/Room/Other,Basic Educational Services,NaN,NaN,NaN,Line Item that is paid with Campus' money,School,NaN,Instruction,NaN,NaN,3999.910000,NaN,NaN,General Fund,NaN
1,28872,Extra Duty/Signing Bonus Pay,Undistributed,NaN,CHEERLEADER DIR,NaN,General,School,NaN,Cocurricular & Extra Curricular Activities,NaN,NaN,3447.320213,NaN,NaN,General Fund,NaN
2,186915,Professional Salaries,Bilingual Education,NaN,T-EL 1ST BIL,NaN,General,School,1.0,Instruction,NaN,NaN,52738.780869,NaN,NaN,General Fund,NaN
3,412396,Professional Salaries,Bilingual Education,NaN,T-EL 2ND BIL,NaN,General,School,1.0,Instruction,NaN,NaN,69729.263191,NaN,NaN,General Fund,NaN
4,427740,Salaries for Support Personnel,Undistributed,NaN,CLERK III- SCH,NaN,General,School,1.0,School Leadership,NaN,NaN,29492.834215,NaN,NaN,General Fund,NaN
5,69847,General Supplies,Gifted and Talented,NaN,NaN,NaN,Magnet School,School,NaN,School Leadership,NaN,NaN,611.730000,NaN,NaN,General Fund,NaN
6,358824,Maint: Vehicles,Special Education,NaN,NaN,NaN,General,Transportation Office,NaN,Student Transportation,NaN,NaN,45999.960000,NaN,NaN,General Fund,NaN
7,254148,Extra Duty/Signing Bonus Pay,Special Education,NaN,NaN,NaN,General,Special Ed Evaluation Services,NaN,"Guidance, Counseling and Evaluation Services",NaN,NaN,9342.409000,NaN,NaN,IDEA-B Formula,NaN
8,296,General Supplies,Basic Educational Services,NaN,NaN,NaN,Art,School,NaN,Instruction,NaN,NaN,1480.970000,NaN,NaN,General Fund,NaN
9,416755,Salaries for Support Personnel,Undistributed,NaN,FOOD PROD SP II,NaN,General,School,0.5,Food Services,NaN,NaN,13675.591718,NaN,NaN,Nat'l Schl Breakfast & Lunch Prog.,NaN
10,179714,Salaries for Support Personnel,Special Education,NaN,TCHR ASST- SP E,NaN,General,School,1.0,Instruction,NaN,NaN,38206.268900,NaN,NaN,General Fund,NaN
11,285896,Salaries for Support Personnel,Special Education,NaN,TCHR ASST- SP E,NaN,General,ABD,1.0,Instruction,NaN,NaN,30583.746336,NaN,NaN,IDEA-B Formula,NaN
12,265808,Reading Materials including Library Books,Undistributed,NaN,NaN,NaN,Line Item that is paid with Campus' money,School,NaN,Curriculum & Instructional Staff Development,NaN,NaN,650.720000,NaN,NaN,General Fund,NaN
13,197775,Professional Salaries,Basic Educational Services,NaN,T-HS P.E.,NaN,General,School,1.0,Instruction,NaN,NaN,57037.432709,NaN,NaN,General Fund,NaN
14,204524,Extra Duty/Signing Bonus Pay,Bilingual Education,NaN,NaN,NaN,General,School,NaN,Instruction,NaN,NaN,11450.850204,NaN,NaN,General Fund,NaN
15,229744,Professional Salaries,Bilingual Education,NaN,T-EL 1ST ESL,NaN,General,School,1.0,Instruction,NaN,NaN,56226.718197,NaN,NaN,General Fund,NaN
16,30711,Employee Allowance,Basic Educational Services,NaN,TRAVEL,NaN,General,School,NaN,Instruction,NaN,NaN,433.267707,NaN,NaN,General Fund,NaN
17,220894,Part-Time Hourly,Accelerated Education,NaN,NaN,NaN,General,School,NaN,Community Services,NaN,NaN,49792.634000,NaN,NaN,English Literacy Civics,NaN
18,7061,Salaries for Support Personnel,Undistributed,NaN,ACCTG TECH III,NaN,General,State/Federal Compliance & Accountability,0.5,Instructional Leadership,NaN,NaN,21998.639555,NaN,NaN,General Fund,NaN
19,4824,Part-Time Hourly,Undistributed,NaN,NaN,NaN,Line Item that is paid with Campus' money,School,NaN,Security & Monitoring Servicess,NaN,NaN,4963.147023,NaN,NaN,General Fund,NaN

In [4]:
budget_test.head()

,Unnamed: 0,Object_Description,Program_Description,SubFund_Description,Job_Title_Description,Facility_or_Department,Sub_Object_Description,Location_Description,FTE,Function_Description,Position_Extra,Text_4,Total,Text_2,Text_3,Fund_Description,Text_1
0,180042,Student Meals/Room/Other,Basic Educational Services,NaN,NaN,NaN,Line Item that is paid with Campus' money,School,NaN,Instruction,NaN,NaN,3999.910000,NaN,NaN,General Fund,NaN
1,28872,Extra Duty/Signing Bonus Pay,Undistributed,NaN,CHEERLEADER DIR,NaN,General,School,NaN,Cocurricular & Extra Curricular Activities,NaN,NaN,3447.320213,NaN,NaN,General Fund,NaN
2,186915,Professional Salaries,Bilingual Education,NaN,T-EL 1ST BIL,NaN,General,School,1.0,Instruction,NaN,NaN,52738.780869,NaN,NaN,General Fund,NaN
3,412396,Professional Salaries,Bilingual Education,NaN,T-EL 2ND BIL,NaN,General,School,1.0,Instruction,NaN,NaN,69729.263191,NaN,NaN,General Fund,NaN
4,427740,Salaries for Support Personnel,Undistributed,NaN,CLERK III- SCH,NaN,General,School,1.0,School Leadership,NaN,NaN,29492.834215,NaN,NaN,General Fund,NaN

In [5]:
Function = pd.read_csv('../data/function_probability.csv', index_col=0)
Use = pd.read_csv('../data/use_probability.csv', index_col=0)
Sharing = pd.read_csv('../data/sharing_probability.csv', index_col=0)
Reporting = pd.read_csv('../data/reporting_probability.csv', index_col=0)
Student_Type = pd.read_csv('../data/student_type_probability.csv', index_col=0)
Position_Type = pd.read_csv('../data/position_probability.csv', index_col=0)
Object_Type = pd.read_csv('../data/object_probability.csv', index_col=0)
Pre_K = pd.read_csv('../data/preK_probability.csv', index_col=0)
Operating_Status = pd.read_csv('../data/op_stat_probability.csv', index_col=0)

In [9]:
results = pd.concat([budget_test, Function, Object_Type, Operating_Status, Position_Type, Pre_K, Reporting,\
                     Sharing, Student_Type, Use], axis = 1)

In [10]:
results.shape

(50064, 121)

In [11]:
results = results.drop(predictors, axis=1)

In [12]:
results.shape

(50064, 105)

In [13]:
results.to_csv('initial_submission.csv')